steps:
# Build release container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/python-example-$BUILD_ID', '.']

# Build testing container
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '--target=test', '-t', 'gcr.io/$PROJECT_ID/python-example-$BUILD_ID-test', '.']

# Run unit tests
- name: 'gcr.io/$PROJECT_ID/python-example-$BUILD_ID-test'

images: ['gcr.io/$PROJECT_ID/python-example-$BUILD_ID']
